### ISSUE TITLE
Code review #1

### ISSUE THREAD

**Issue by rimus** [zohids/wdio-practical-tasks#1]
1. node_modules directory should be ignored in .gitignore file.
2. Following the task you should use Page Object concept. There is no PO in your tests. Please fix. Read more: https://webdriver.io/docs/pageobjects/ and https://learn.epam.com/study/path?rootId=1135268&moduleId=1135340&tab=COURSEWARE
3. Locators copied from the devtolls (like `/html/body/span[2]/span/span[2]/ul/li[2]/ul/li[1]`) are not acceptable. Please use more stable ways or options to get it.
4. Fixes should be added in a separate branch and create Pull request, after it book a new call on a Booking platform.

**Comment by zohids** [comment]
I don't have access to this link:
https://learn.epam.com/study/path?rootId=1135268&moduleId=1135340&tab=COURSEWARE

**Comment by rimus** [comment]
Ok, you can try to open this from your learning course:
![изображение](https://github.com/zohids/wdio-practical-tasks/assets/13272361/6428c2fa-6662-4701-bdf2-4142a6f01efc)

**Comment by rimus** [comment]
Task is accepted.
